# =============================================================================
# Dockerfile for Airflow with Windows Authentication (Kerberos) Support
# =============================================================================
FROM apache/airflow:3.2.1

USER root

ENV DEBIAN_FRONTEND=noninteractive

# Set timezone to Tehran
ENV TZ=Asia/Tehran

# Install Kerberos client and dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    krb5-user \
    libkrb5-dev \
    gcc \
    g++ \
    unixodbc \
    unixodbc-dev \
    curl \
    gnupg2 \
    librdkafka-dev \
    default-libmysqlclient-dev \
    # apt-transport-https \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Microsoft ODBC Driver 18 for SQL Server
RUN curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg \
    # && curl -fsSL https://packages.microsoft.com/config/debian/12/prod.list | tee /etc/apt/sources.list.d/mssql-release.list \
    && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/debian/12/prod bookworm main" \
    > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow

ARG AIRFLOW_VERSION=3.2.1
ARG PYTHON_VERSION=3.12

ENV CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

# Install Python packages
RUN pip install --no-cache-dir \
    pyodbc \
    pymssql \
    apache-airflow-providers-microsoft-mssql \
    confluent-kafka \
    avro-python3 \
    fastavro \
    apache-airflow-providers-apache-kafka \
    clickhouse-driver \
    pymongo \
    mysqlclient \
    apache-airflow-providers-mysql \
    apache-airflow-providers-common-sql \
    apache-airflow-providers-postgres \
    psycopg2-binary \
    apache-airflow-providers-hashicorp \
    apache-airflow-providers-http \
    --constraint "${CONSTRAINT_URL}"

ENV AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Tehran
