# =============================================================================
# Airflow 3.0.6 with Kerberos + MSSQL + Kafka + MySQL + Postgres support
# =============================================================================

FROM apache/airflow:3.0.6

USER root

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=Asia/Tehran

# Install Kerberos client and dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    krb5-user \
    libkrb5-dev \
    gcc \
    g++ \
    unixodbc \
    unixodbc-dev \
    curl \
    gnupg2 \
    librdkafka-dev \
    default-libmysqlclient-dev \
    # apt-transport-https \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Microsoft ODBC Driver 18 for SQL Server
RUN curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg \
    # && curl -fsSL https://packages.microsoft.com/config/debian/12/prod.list | tee /etc/apt/sources.list.d/mssql-release.list \
    && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/debian/12/prod bookworm main" \
    > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql18 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow

ARG AIRFLOW_VERSION=3.0.6
ARG PYTHON_VERSION=3.11

ENV CONSTRAINT_URL="https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"

# Python dependencies
RUN --mount=type=cache,target=/home/airflow/.cache/pip \
    pip install --no-cache-dir \
    pyodbc \
    pymssql \
    apache-airflow-providers-microsoft-mssql \
    confluent-kafka \
    avro-python3 \
    fastavro \
    apache-airflow-providers-apache-kafka \
    clickhouse-driver \
    # apache-airflow-providers-clickhouse \
    mysqlclient \
    apache-airflow-providers-mysql \
    apache-airflow-providers-common-sql \
    apache-airflow-providers-postgres \
    apache-airflow-providers-hashicorp \
    apache-airflow-providers-http \
    --constraint "${CONSTRAINT_URL}"

# RUN pip install "apache-airflow-providers-clickhouse @ git+https://github.com/apache/airflow.git#subdirectory=providers/clickhouse"

ENV AIRFLOW__CORE__DEFAULT_TIMEZONE=Asia/Tehran
